# human_type = [
#     'Squire',
#     'Knight',
#     'Archer',
#     'Priest',
#     'Wizard',
#     'Thief',
#     'Druid',
#     'Red Dragon',
#     'Black Dragon',
# ]

human_type = {
    'Squire': {'name': 'Squire',
               'life': 250,
               'attack': 190,
               'defense': 60,
               'level': 6,
               'xp': 250,
               'crit_chance': 15,
               'image': 'assets/images/enemies/squire.png'},

    'Knight': {'name': 'Knight',
               'life': 350,
               'attack': 260,
               'defense': 85,
               'level': 11,
               'xp': 300,
               'crit_chance': 20,
               'image': 'assets/images/enemies/knight.png'},

    'Archer': {'name': 'Archer',
               'life': 380,
               'attack': 280,
               'defense': 75,
               'level': 12,
               'xp': 400,
               'crit_chance': 70,
               'image': 'assets/images/enemies/archer.png'},

    'Black Mage': {'name': 'Black Mage',
                   'life': 400,
                   'attack': 350,
                   'defense': 60,
                   'level': 13,
                   'xp': 500,
                   'crit_chance': 20,
                   'image': 'assets/images/enemies/black_mage.png'},

    'Monk': {'name': 'Monk',
             'life': 500,
             'attack': 500,
             'defense': 50,
             'level': 14,
             'xp': 700,
             'crit_chance': 15,
             'image': 'assets/images/enemies/monk.png'},

    'Time Mage': {'name': 'Time Mage',
                  'life': 500,
                  'attack': 400,
                  'defense': 70,
                  'level': 15,
                  'xp': 800,
                  'crit_chance': 20,
                  'image': 'assets/images/enemies/time_mage.png'},

    'Geomancer': {'name': 'Geomancer',
                  'life': 600,
                  'attack': 600,
                  'defense': 70,
                  'level': 16,
                  'xp': 850,
                  'crit_chance': 0,
                  'image': 'assets/images/enemies/geomancer.png'},

    'Summoner': {'name': 'Summoner',
                 'life': 650,
                 'attack': 750,
                 'defense': 60,
                 'level': 17,
                 'xp': 950,
                 'crit_chance': 0,
                 'image': 'assets/images/enemies/summoner.png'},

    'Samurai': {'name': 'Samurai',
                'life': 700,
                'attack': 700,
                'defense': 100,
                'level': 18,
                'xp': 1200,
                'crit_chance': 0,
                'image': 'assets/images/enemies/samurai.png'},

    'Ninja': {'name': 'Ninja',
              'life': 700,
              'attack': 650,
              'defense': 80,
              'level': 19,
              'xp': 1200,
              'crit_chance': 40,
              'image': 'assets/images/enemies/ninja.png'},

    'Dark Archer': {'name': 'Dark Archer',
                    'life': 900,
                    'attack': 700,
                    'defense': 130,
                    'level': 20,
                    'xp': 1700,
                    'crit_chance': 80,
                    'image': 'assets/images/enemies/dark_archer.png'},

    'Dark Samurai': {'name': 'Dark Samurai',
                     'life': 1300,
                     'attack': 900,
                     'defense': 200,
                     'level': 21,
                     'xp': 2000,
                     'crit_chance': 0,
                     'image': 'assets/images/enemies/dark_samurai.png'}

}
