from items.consumables import *

monster_type = {
    'Green Goblin': {'name': 'Green Goblin',
                     'life': 80,
                     'attack': 104,
                     'defense': 12,
                     'level': 1,
                     'xp': 10,
                     'crit_chance': 10,
                     'delve_drop': consumables['dense fossil'],
                     'image': 'assets/images/enemies/green_goblin.png'},

    'Chocobo': {'name': 'Chocobo',
                'life': 85,
                'attack': 108,
                'defense': 13,
                'level': 1,
                'xp': 13,
                'crit_chance': 20,
                'delve_drop': consumables['dense fossil'],
                'image': 'assets/images/enemies/chocobo.png'},

    'Skeleton': {'name': 'Skeleton',
                 'life': 90,
                 'attack': 115,
                 'defense': 15,
                 'level': 2,
                 'xp': 15,
                 'crit_chance': 10,
                 'delve_drop': consumables['dense fossil'],
                 'image': 'assets/images/enemies/skeleton.png'},

    'Red Panther': {'name': 'Red Panther',
                    'life': 95,
                    'attack': 120,
                    'defense': 20,
                    'level': 2,
                    'xp': 18,
                    'crit_chance': 15,
                    'delve_drop': consumables['dense fossil'],
                    'image': 'assets/images/enemies/red_panther.png'},

    'Black Chocobo': {'name': 'Black Chocobo',
                      'life': 98,
                      'attack': 125,
                      'defense': 20,
                      'level': 3,
                      'xp': 18,
                      'crit_chance': 25,
                      'delve_drop': consumables['dense fossil'],
                      'image': 'assets/images/enemies/black_chocobo.png'},

    'Red Goblin': {'name': 'Red Goblin',
                   'life': 100,
                   'attack': 130,
                   'defense': 23,
                   'level': 3,
                   'xp': 25,
                   'crit_chance': 10,
                   'delve_drop': consumables['dense fossil'],
                   'image': 'assets/images/enemies/goblin.png'},

    'Coeurl': {'name': 'Coeurl',
               'life': 105,
               'attack': 140,
               'defense': 23,
               'level': 4,
               'xp': 25,
               'crit_chance': 20,
               'delve_drop': consumables['dense fossil'],
               'image': 'assets/images/enemies/coeurl.png'},

    'Bonesnatch': {'name': 'Bonesnatch',
                   'life': 110,
                   'attack': 145,
                   'defense': 30,
                   'level': 4,
                   'xp': 35,
                   'crit_chance': 10,
                   'delve_drop': consumables['dense fossil'],
                   'image': 'assets/images/enemies/bonesnatch.png'},

    'Black Goblin': {'name': 'Black Goblin',
                     'life': 125,
                     'attack': 147,
                     'defense': 30,
                     'level': 5,
                     'xp': 45,
                     'crit_chance': 10,
                     'delve_drop': consumables['serrated fossil'],
                     'image': 'assets/images/enemies/black_goblin.png'},

    'Red Chocobo': {'name': 'Red Chocobo',
                    'life': 130,
                    'attack': 150,
                    'defense': 35,
                    'level': 5,
                    'xp': 50,
                    'crit_chance': 30,
                    'delve_drop': consumables['serrated fossil'],
                    'image': 'assets/images/enemies/red_chocobo.png'},

    'Vampire Cat': {'name': 'Vampire Cat',
                    'life': 135,
                    'attack': 155,
                    'defense': 37,
                    'level': 6,
                    'xp': 70,
                    'crit_chance': 25,
                    'delve_drop': consumables['serrated fossil'],
                    'image': 'assets/images/enemies/vampire_cat.png'},

    'Gobbledygook': {'name': 'Gobbledygook',
                     'life': 140,
                     'attack': 155,
                     'defense': 40,
                     'level': 6,
                     'xp': 90,
                     'crit_chance': 15,
                     'delve_drop': consumables['serrated fossil'],
                     'image': 'assets/images/enemies/gobbledygook.png'},

    'Skeletal Fiend': {'name': 'Skeletal Fiend',
                       'life': 145,
                       'attack': 165,
                       'defense': 40,
                       'level': 7,
                       'xp': 100,
                       'crit_chance': 15,
                       'delve_drop': consumables['serrated fossil'],
                       'image': 'assets/images/enemies/skeletal_fiend.png'},

    'Ghoul': {'name': 'Ghoul',
              'life': 100,
              'attack': 170,
              'defense': 10,
              'level': 7,
              'xp': 150,
              'crit_chance': 50,
              'delve_drop': consumables['serrated fossil'],
              'image': 'assets/images/enemies/ghoul.png'},

    'Floating Eye': {'name': 'Floating Eye',
                     'life': 220,
                     'attack': 175,
                     'defense': 46,
                     'level': 8,
                     'xp': 200,
                     'crit_chance': 20,
                     'delve_drop': consumables['serrated fossil'],
                     'image': 'assets/images/enemies/floating_eye.png'},

    'Ghast': {'name': 'Ghast',
              'life': 150,
              'attack': 180,
              'defense': 20,
              'level': 8,
              'xp': 220,
              'crit_chance': 50,
              'delve_drop': consumables['serrated fossil'],
              'image': 'assets/images/enemies/ghast.png'},

    'Piscodaemon': {'name': 'Piscodaemon',
                    'life': 260,
                    'attack': 195,
                    'defense': 50,
                    'level': 9,
                    'xp': 250,
                    'crit_chance': 30,
                    'delve_drop': consumables['serrated fossil'],
                    'image': 'assets/images/enemies/piscodaemon.png'},

    'Squidrakin': {'name': 'Squidrakin',
                   'life': 280,
                   'attack': 200,
                   'defense': 65,
                   'level': 10,
                   'xp': 300,
                   'crit_chance': 40,
                   'delve_drop': consumables['pristine fossil'],
                   'image': 'assets/images/enemies/squidrakin.png'},

    'Ahriman': {'name': 'Ahriman',
                'life': 280,
                'attack': 220,
                'defense': 65,
                'level': 10,
                'xp': 320,
                'crit_chance': 30,
                'delve_drop': consumables['pristine fossil'],
                'image': 'assets/images/enemies/ahriman.png'},

    'Mindflayer': {'name': 'Mindflayer',
                   'life': 300,
                   'attack': 250,
                   'defense': 70,
                   'level': 11,
                   'xp': 380,
                   'crit_chance': 50,
                   'delve_drop': consumables['pristine fossil'],
                   'image': 'assets/images/enemies/mindflare.png'},

    'Plague Horror': {'name': 'Plague Horror',
                      'life': 350,
                      'attack': 270,
                      'defense': 80,
                      'level': 11,
                      'xp': 400,
                      'crit_chance': 40,
                      'delve_drop': consumables['pristine fossil'],
                      'image': 'assets/images/enemies/plague_of_horror.png'},

    'Dryad': {'name': 'Dryad',
              'life': 600,
              'attack': 260,
              'defense': 100,
              'level': 12,
              'xp': 450,
              'crit_chance': 0,
              'delve_drop': consumables['pristine fossil'],
              'image': 'assets/images/enemies/dryad.png'},

    'Jura Aevis': {'name': 'Jura Aevis',
                   'life': 400,
                   'attack': 300,
                   'defense': 80,
                   'level': 12,
                   'xp': 450,
                   'crit_chance': 50,
                   'delve_drop': consumables['pristine fossil'],
                   'image': 'assets/images/enemies/jura_aevis.png'},

    'Revenant': {'name': 'Revenant',
                 'life': 400,
                 'attack': 300,
                 'defense': 40,
                 'level': 13,
                 'xp': 450,
                 'crit_chance': 50,
                 'delve_drop': consumables['pristine fossil'],
                 'image': 'assets/images/enemies/revenant.png'},

    'Steelhawk': {'name': 'Steelhawk',
                  'life': 450,
                  'attack': 340,
                  'defense': 90,
                  'level': 13,
                  'xp': 500,
                  'crit_chance': 50,
                  'delve_drop': consumables['pristine fossil'],
                  'image': 'assets/images/enemies/steelhawk.png'},

    'Treant': {'name': 'Treant',
               'life': 900,
               'attack': 270,
               'defense': 120,
               'level': 14,
               'xp': 600,
               'crit_chance': 0,
               'delve_drop': consumables['pristine fossil'],
               'image': 'assets/images/enemies/treant.png'},

    'Cockatrice': {'name': 'Cockatrice',
                   'life': 600,
                   'attack': 370,
                   'defense': 100,
                   'level': 14,
                   'xp': 650,
                   'crit_chance': 50,
                   'delve_drop': consumables['pristine fossil'],
                   'image': 'assets/images/enemies/cockatrice.png'},

    'Wisenkin': {'name': 'Wisenkin',
                 'life': 650,
                 'attack': 420,
                 'defense': 120,
                 'level': 15,
                 'xp': 700,
                 'crit_chance': 15,
                 'delve_drop': consumables['deft fossil'],
                 'image': 'assets/images/enemies/wisenkin.png'},

    'Elder Treant': {'name': 'Elder Treant',
                     'life': 1500,
                     'attack': 350,
                     'defense': 140,
                     'level': 16,
                     'xp': 800,
                     'crit_chance': 0,
                     'delve_drop': consumables['deft fossil'],
                     'image': 'assets/images/enemies/elder_treant.png'},

    'Minotaur': {'name': 'Minotaur',
                 'life': 900,
                 'attack': 500,
                 'defense': 140,
                 'level': 17,
                 'xp': 1000,
                 'crit_chance': 25,
                 'delve_drop': consumables['deft fossil'],
                 'image': 'assets/images/enemies/minotaur.png'},

    'Malboro': {'name': 'Malboro',
                'life': 1400,
                'attack': 500,
                'defense': 150,
                'level': 18,
                'xp': 1200,
                'crit_chance': 15,
                'delve_drop': consumables['deft fossil'],
                'image': 'assets/images/enemies/malboro.png'},

    'Behemoth': {'name': 'Behemoth',
                 'life': 1800,
                 'attack': 550,
                 'defense': 160,
                 'level': 19,
                 'xp': 1400,
                 'crit_chance': 25,
                 'delve_drop': consumables['deft fossil'],
                 'image': 'assets/images/enemies/behemoth.png'},

    'Dark Behemoth': {'name': 'Dark Behemoth',
                      'life': 2100,
                      'attack': 600,
                      'defense': 170,
                      'level': 20,
                      'xp': 1500,
                      'crit_chance': 25,
                      'delve_drop': consumables['deft fossil'],
                      'image': 'assets/images/enemies/dark_behemoth.png'},

    'Blue Dragon': {'name': 'Blue Dragon',
                    'life': 2500,
                    'attack': 700,
                    'defense': 200,
                    'level': 21,
                    'xp': 1800,
                    'crit_chance': 25,
                    'delve_drop': consumables['fractured fossil'],
                    'image': 'assets/images/enemies/blue_dragon.png'},

    'Tiamat': {'name': 'Tiamat',
               'life': 3000,
               'attack': 750,
               'defense': 220,
               'level': 22,
               'xp': 2500,
               'crit_chance': 0,
               'delve_drop': consumables['fractured fossil'],
               'image': 'assets/images/enemies/tiamat.png'}
    #
    # 'Ruby Weapon': {'name': 'Ruby Weapon',
    #            'life': 10000,
    #            'attack': 800,
    #            'defense': 450,
    #            'level': 22,
    #            'xp': 10500,
    #            'crit_chance': 0,
    #            'delve_drop': consumables['fractured fossil'],
    #            'image': 'assets/images/enemies/ruby_weapon.png'}
}
