boots_type = [
    {'type': 'boots', 'name': 'Simple Boots',  'life': 1, 'attack': 1, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0,  'level': 1, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Power Boots',  'life': 5, 'attack': 3, 'defense': 2, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 2, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Magepower Boots',  'life': 10, 'attack': 2, 'defense': 3, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 4, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': "Soldier's Boots",  'life': 15, 'attack': 3, 'defense': 4, 'crit_chance': 5, 'crit_damage': 0, 'magic_find': 0, 'level': 6, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': "Brigand's Boots",  'life': 25, 'attack': 5, 'defense': 6, 'crit_chance': 5, 'crit_damage': 0, 'magic_find': 0, 'level': 8, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Onion Boots',  'life': 35, 'attack': 6, 'defense': 8, 'crit_chance': 5, 'crit_damage': 0, 'magic_find': 0, 'level': 10, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Mythril Boots',  'life': 50, 'attack': 8, 'defense': 11, 'crit_chance': 7, 'crit_damage': 0, 'magic_find': 0, 'level': 12, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Dragon Boots',  'life': 70, 'attack': 12, 'defense': 15, 'crit_chance': 7, 'crit_damage': 0, 'magic_find': 0, 'level': 14, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': "Moogle's Boots",  'life': 100, 'attack': 14, 'defense': 17, 'crit_chance': 8, 'crit_damage': 0, 'magic_find': 0, 'level': 16, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Timeworn Boots',  'life': 140, 'attack': 13, 'defense': 15, 'crit_chance': 8, 'crit_damage': 0, 'magic_find': 0, 'level': 18, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'boots', 'name': 'Gengi Boots',  'life': 120, 'attack': 20, 'defense': 20, 'crit_chance': 8, 'crit_damage': 0, 'magic_find': 0, 'level': 20, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_amulet.png'}
]