consumables = {
    'potion': {'type': 'consumable',
               'name': 'Potion',
               'value': 300,
               'quantity': 0,
               'drop_rate': 40,
               'rarity': 'common',
               'code': 1,
               'sound': 'assets/music/consumable.wav'},

    'hi-potion': {'type': 'consumable',
                  'name': 'Hi-Potion',
                  'value': 1000,
                  'quantity': 0,
                  'drop_rate': 20,
                  'rarity': 'incommon',
                  'code': 2,
                  'sound': 'assets/music/consumable.wav'},

    'x-potion': {'type': 'consumable',
                 'name': 'X-Potion',
                 'value': 2000,
                 'quantity': 0,
                 'drop_rate': 20,
                 'rarity': 'rare',
                 'code': 3,
                 'sound': 'assets/music/consumable.wav'},

    'elixir': {'type': 'consumable',
               'name': 'Elixir',
               'value': 99999,
               'quantity': 0,
               'drop_rate': 0,
               'rarity': 'super rare',
               'code': 4,
               'sound': 'assets/music/consumable.wav'},

    'chaos orb': {'type': 'consumable',
                  'name': 'Chaos Orb',
                  'value': 2,
                  'quantity': 0,
                  'drop_rate': 5,
                  'rarity': 'super rare',
                  'code': 5,
                  'sound': 'assets/music/consumable.wav'},

    'divine orb': {'type': 'consumable',
                   'name': 'Divine Orb',
                   'value': 2,
                   'quantity': 0,
                   'drop_rate': 5,
                   'rarity': 'super rare',
                   'code': 6,
                   'sound': 'assets/music/consumable.wav'},

    'exalted orb': {'type': 'consumable',
                    'name': 'Exalted Orb',
                    'value': 100,
                    'quantity': 0,
                    'drop_rate': 5,
                    'rarity': 'super rare',
                    'code': 7,
                    'sound': 'assets/music/consumable.wav'},

    'mirror of kalandra': {'type': 'consumable',
                           'name': 'Mirror of Kalandra',
                           'value': '300, 10, 10',
                           'quantity': 0,
                           'drop_rate': 0.4,
                           'rarity': 'mythic rare',
                           'code': 8,
                           'sound': 'assets/music/mirror_of_kalandra.mp3'},

    'dense fossil': {'type': 'fossil',
                     'name': 'Dense Fossil',
                     'value': 20,
                     'quantity': 0,
                     'drop_rate': 0.4,
                     'rarity': 'mythic rare',
                     'code': 9,
                     'sound': 'assets/music/consumable.wav',
                     'attribute': 'defense'},

    'serrated fossil': {'type': 'fossil',
                        'name': 'Serrated Fossil',
                        'value': 20,
                        'quantity': 0,
                        'drop_rate': 0.4,
                        'rarity': 'mythic rare',
                        'code': 10,
                        'sound': 'assets/music/consumable.wav',
                        'attribute': 'attack'},

    'pristine fossil': {'type': 'fossil',
                        'name': 'Pristine Fossil',
                        'value': 30,
                        'quantity': 0,
                        'drop_rate': 0.4,
                        'rarity': 'mythic rare',
                        'code': 11,
                        'sound': 'assets/music/consumable.wav',
                        'attribute': 'life'},

    'deft fossil': {'type': 'fossil',
                    'name': 'Deft Fossil',
                    'value': 10,
                    'quantity': 0,
                    'drop_rate': 0.4,
                    'rarity': 'mythic rare',
                    'code': 12,
                    'sound': 'assets/music/consumable.wav',
                    'attribute': 'crit_damage'},

    'fractured fossil': {'type': 'fossil',
                         'name': 'Fractured Fossil',
                         'value': 10,
                         'quantity': 0,
                         'drop_rate': 0.4,
                         'rarity': 'mythic rare',
                         'code': 13,
                         'sound': 'assets/music/consumable.wav',
                         'attribute': 'attack, defense, life, critical chance'},

    'roulette_wheel_ticket': {'type': 'consumable',
                         'name': 'Roulette Wheel Ticket',
                         'value': 1,
                         'quantity': 10,
                         'drop_rate': 0.4,
                         'rarity': 'mythic rare',
                         'code': 14,
                         'sound': 'assets/music/consumable.wav',
                         'attribute': 'prize'}

}
