helmet_type = [
    {'type': 'helmet', 'name': 'Wooden Helm', 'life': 1, 'attack': 0, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0,  'level': 1, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Bronze Hat', 'life': 3, 'attack': 0, 'defense': 2, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0,  'level': 2, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Silver Hat', 'life': 5, 'attack': 0, 'defense': 4, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 3, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Golden Hat', 'life': 10, 'attack': 0, 'defense': 5, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 5, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Gengi Hat', 'life': 15, 'attack': 0, 'defense': 7, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 7, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Bronze Helm', 'life': 22, 'attack': 0, 'defense': 10, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 9, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Silver Helm', 'life': 30, 'attack': 0, 'defense': 15, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 11, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Golden Helm', 'life': 40, 'attack': 0, 'defense': 22, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 13, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Gengi Helm', 'life': 50, 'attack': 0, 'defense': 28, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 15, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Bronze Circlet', 'life': 70, 'attack': 0, 'defense': 38, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 16, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Silver Circlet', 'life': 90, 'attack': 0, 'defense': 50, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 17, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Golden Circlet', 'life': 100, 'attack': 0, 'defense': 65, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 18, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'helmet', 'name': 'Gengi Circlet', 'life': 110, 'attack': 0, 'defense': 80, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 20, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_knife.png'}
]
