ring_type = [
    {'type': 'ring', 'name': 'Wooden Ring',  'life': 1, 'attack': 1, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 1, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': 'Protect Ring',  'life': 4, 'attack': 3, 'defense': 2, 'crit_chance': 3, 'crit_damage': 3, 'magic_find': 0, 'level': 2, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': 'Magick Ring',  'life': 8, 'attack': 5, 'defense': 3, 'crit_chance': 3, 'crit_damage': 3, 'magic_find': 0, 'level': 3, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': 'Reflect Ring',  'life': 12, 'attack': 7, 'defense': 4, 'crit_chance': 3, 'crit_damage': 3, 'magic_find': 0, 'level': 4, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': 'Angel Ring',  'life': 16, 'attack': 9, 'defense': 5, 'crit_chance': 5, 'crit_damage': 5, 'magic_find': 0, 'level': 6, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': 'Cursed Ring',  'life': 20, 'attack': 11, 'defense': 6, 'crit_chance': 5, 'crit_damage': 5, 'magic_find': 0, 'level': 8, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Sage's Ring",  'life': 24, 'attack': 12, 'defense': 7, 'crit_chance': 5, 'crit_damage': 5, 'magic_find': 0, 'level': 10, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Mythril Ring",  'life': 30, 'attack': 14, 'defense': 8, 'crit_chance': 5, 'crit_damage': 5, 'magic_find': 0, 'level': 12, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Dragon Ring",  'life': 40, 'attack': 18, 'defense': 10, 'crit_chance': 5, 'crit_damage': 5, 'magic_find': 0, 'level': 14, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Lionheart Ring",  'life': 60, 'attack': 20, 'defense': 12, 'crit_chance': 7, 'crit_damage': 7, 'magic_find': 0, 'level': 16, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Moogle's Ring", 'life': 80, 'attack': 22, 'defense': 14, 'crit_chance': 7, 'crit_damage': 7, 'magic_find': 0, 'level': 18, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Timeworn Ring", 'life': 120, 'attack': 22, 'defense': 14, 'crit_chance': 7, 'crit_damage': 7, 'magic_find': 0, 'level': 19, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'},
    {'type': 'ring', 'name': "Genji Ring", 'life': 100, 'attack': 30, 'defense': 16, 'crit_chance': 8, 'crit_damage': 8, 'magic_find': 0, 'level': 20, 'rarity': 'common', 'image': 'assets/images/items/weapons/wooden_amulet.png'}
]