weapon_type = [
    {'type': 'weapon', 'name': 'Wooden Knife',  'life': 0, 'attack': 1, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0,  'level': 1, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Wand',  'life': 0, 'attack': 2, 'defense': 1, 'crit_chance': 10, 'crit_damage': 10, 'magic_find': 0,  'level': 2, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Staff',  'life': 0, 'attack': 4, 'defense': 5, 'crit_chance': 10, 'crit_damage': 10, 'magic_find': 0, 'level': 3, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Club',  'life': 0, 'attack': 8, 'defense': 1, 'crit_chance': 10, 'crit_damage': 10, 'magic_find': 0, 'level': 4, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Mace',  'life': 0, 'attack': 10, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 5, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Sword',  'life': 0, 'attack': 12, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 6, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Axe',  'life': 0, 'attack': 14, 'defense': 1, 'crit_chance': 25, 'crit_damage': 25, 'magic_find': 0, 'level': 7, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Javelin',  'life': 0, 'attack': 16, 'defense': 6, 'crit_chance': 25, 'crit_damage': 25, 'magic_find': 0, 'level': 8, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Spear',  'life': 0, 'attack': 18, 'defense': 7, 'crit_chance': 25, 'crit_damage': 25, 'magic_find': 0, 'level': 9, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Bow',  'life': 0, 'attack': 18, 'defense': 1, 'crit_chance': 30, 'crit_damage': 30, 'magic_find': 0, 'level': 10, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Mythril Bow',  'life': 0, 'attack': 22, 'defense': 1, 'crit_chance': 30, 'crit_damage': 30, 'magic_find': 0, 'level': 11, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Defender',  'life': 0, 'attack': 30, 'defense': 15, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 12, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Mythril Sword',  'life': 0, 'attack': 50, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 13, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Artemis Bow',  'life': 0, 'attack': 30, 'defense': 1, 'crit_chance': 35, 'crit_damage': 35, 'magic_find': 0, 'level': 14, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Save the Queen',  'life': 0, 'attack': 60, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 15, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Chirijiraden',  'life': 0, 'attack': 80, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 16, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Yoichi Bow',  'life': 0, 'attack': 40, 'defense': 1, 'crit_chance': 35, 'crit_damage': 35, 'magic_find': 0, 'level': 17, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Excalibur',  'life': 0, 'attack': 80, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 18, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Masamune',  'life': 0, 'attack': 140, 'defense': 1, 'crit_chance': 0, 'crit_damage': 0, 'magic_find': 0, 'level': 19, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Chaos Blade',  'life': 0, 'attack': 120, 'defense': 1, 'crit_chance': 20, 'crit_damage': 20, 'magic_find': 0, 'level': 20, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'},
    {'type': 'weapon', 'name': 'Genji Bow',  'life': 0, 'attack': 70, 'defense': 1, 'crit_chance': 40, 'crit_damage': 40, 'magic_find': 0, 'level': 20, 'rarity': 'common', 'crafted': 0, 'image': 'assets/images/items/weapons/wooden_knife.png'}
]


